### ISSUE TITLE
초기 카테고리 편집 View

### ISSUE THREAD

**Issue by akrudal** [recody-project/Recody_front#16]
### 📃 Description
카테고리 편집 view를 만든다.
view자체는 어려울게 없어보이는데 그 안에 다양한 제스쳐들을 적용해야 한다.

### ✔ Todo
- [ ] collectionView를 사용하여 카테고리들을 나열한다.
- [ ] 전체 카테고리와 + 버튼은 따로 만든다. (기능이 조금 다르기 때문)
- [ ] long press 이벤트를 적용한다.
- [ ] touch 이벤트를 적용한다.

### 🔴 ETC
기타 사항을 적어주세요.
예상 개발 기간: 6시간
